apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-dashboard
  template:
    metadata:
      labels:
        app: server-dashboard
    spec:
      containers:
        - name: server-dashboard
          image: server-dashboard:local
          imagePullPolicy: Never
          ports:
            - containerPort: 5000